/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationPharmacist = IDL.Record({
  'id' : IDL.Text,
  'dateOfLeaving' : IDL.Text,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'dateOfJoining' : IDL.Text,
  'address' : IDL.Text,
  'resignationDate' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'qualification' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'New' : IDL.Null,
  'OnHold' : IDL.Null,
  'UnderReview' : IDL.Null,
  'FeesReceived' : IDL.Null,
  'DocumentsCollected' : IDL.Null,
  'DocumentsPending' : IDL.Null,
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'ApplicationFiled' : IDL.Null,
  'Completed' : IDL.Null,
  'FeesPending' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'FoodLicenceRenewal' : IDL.Null,
  'DrugLicenceChangePremise' : IDL.Null,
  'MSMEUdyam' : IDL.Null,
  'DrugLicenceNewFirm' : IDL.Null,
  'GSTRegistration' : IDL.Null,
  'DrugLicenceAlterationOfPremise' : IDL.Null,
  'DrugLicenceRemovePharmacist' : IDL.Null,
  'DrugLicenceAddPharmacist' : IDL.Null,
  'FoodLicenceNew' : IDL.Null,
  'Other' : IDL.Null,
  'DrugLicenceChangeConstitution' : IDL.Null,
  'DrugLicenceRenewal' : IDL.Null,
});
export const DocumentItem = IDL.Record({
  'id' : IDL.Nat,
  'isChecked' : IDL.Bool,
  'name' : IDL.Text,
  'checkedAt' : IDL.Opt(IDL.Int),
  'category' : IDL.Text,
});
export const RoomDetail = IDL.Record({
  'whichSide' : IDL.Opt(IDL.Text),
  'length' : IDL.Float64,
  'width' : IDL.Float64,
  'roomName' : IDL.Opt(IDL.Text),
  'entranceSide' : IDL.Opt(IDL.Text),
  'entranceType' : IDL.Text,
});
export const PlanLayoutDetails = IDL.Record({
  'boundaryEast' : IDL.Text,
  'boundaryWest' : IDL.Text,
  'frontOfShop' : IDL.Text,
  'premisesWidth' : IDL.Float64,
  'premisesLength' : IDL.Float64,
  'boundarySouth' : IDL.Text,
  'boundaryNorth' : IDL.Text,
  'rooms' : IDL.Vec(RoomDetail),
});
export const PersonEntry = IDL.Record({
  'id' : IDL.Text,
  'din' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'aadhaarNo' : IDL.Text,
  'address' : IDL.Text,
  'panNo' : IDL.Text,
  'mobile' : IDL.Text,
});
export const TrusteeEntry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'aadhaarNo' : IDL.Text,
  'address' : IDL.Text,
  'panNo' : IDL.Text,
  'mobile' : IDL.Text,
});
export const BusinessTypeData = IDL.Variant({
  'llp' : IDL.Record({ 'designatedPartners' : IDL.Vec(PersonEntry) }),
  'ltd' : IDL.Record({
    'cin' : IDL.Text,
    'directors' : IDL.Vec(PersonEntry),
    'registeredOfficeAddress' : IDL.Text,
  }),
  'pvtLtd' : IDL.Record({
    'cin' : IDL.Text,
    'directors' : IDL.Vec(PersonEntry),
    'registeredOfficeAddress' : IDL.Text,
  }),
  'trust' : IDL.Record({
    'trustName' : IDL.Text,
    'trustees' : IDL.Vec(TrusteeEntry),
    'registrationNo' : IDL.Text,
  }),
  'other' : IDL.Record({
    'otherDescription' : IDL.Text,
    'authorizedPersonName' : IDL.Text,
    'authorizedPersonMobile' : IDL.Text,
    'authorizedPersonAadhaar' : IDL.Text,
    'authorizedPersonAddress' : IDL.Text,
    'authorizedPersonPan' : IDL.Text,
  }),
  'partnership' : IDL.Record({ 'partners' : IDL.Vec(PersonEntry) }),
  'society' : IDL.Record({
    'trustees' : IDL.Vec(TrusteeEntry),
    'registrationNo' : IDL.Text,
    'societyName' : IDL.Text,
  }),
  'proprietary' : IDL.Record({
    'proprietorAddress' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'proprietorMobile' : IDL.Text,
    'aadhaarNo' : IDL.Text,
    'panNo' : IDL.Text,
    'proprietorEmail' : IDL.Text,
    'proprietorName' : IDL.Text,
  }),
});
export const ActivityEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const NoteEntry = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
});
export const PortalCredential = IDL.Record({
  'id' : IDL.Text,
  'portalName' : IDL.Text,
  'directLink' : IDL.Text,
  'userId' : IDL.Text,
  'password' : IDL.Text,
});
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'alterationOldArea' : IDL.Opt(IDL.Float64),
  'status' : ApplicationStatus,
  'expectedCompletionDate' : IDL.Opt(IDL.Int),
  'serviceType' : ServiceType,
  'directLink' : IDL.Opt(IDL.Text),
  'documents' : IDL.Vec(DocumentItem),
  'fdaAddress' : IDL.Text,
  'planLayoutDetails' : IDL.Opt(PlanLayoutDetails),
  'businessTypeData' : IDL.Opt(BusinessTypeData),
  'applicationId' : IDL.Text,
  'amountCollected' : IDL.Nat,
  'createdAt' : IDL.Int,
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'totalFees' : IDL.Nat,
  'selectedFeeTemplates' : IDL.Vec(IDL.Nat),
  'oldPharmacistName' : IDL.Text,
  'email' : IDL.Text,
  'activityLog' : IDL.Vec(ActivityEntry),
  'updatedAt' : IDL.Int,
  'changePremiseNewAddress' : IDL.Opt(IDL.Text),
  'firmId' : IDL.Text,
  'oldPharmacistResignationDate' : IDL.Text,
  'notes' : IDL.Vec(NoteEntry),
  'firmPassword' : IDL.Opt(IDL.Text),
  'pharmacists' : IDL.Vec(ApplicationPharmacist),
  'oldPharmacistRegNo' : IDL.Text,
  'amountPending' : IDL.Nat,
  'portalCredentials' : IDL.Vec(PortalCredential),
  'changePremiseOldAddress' : IDL.Opt(IDL.Text),
  'applicationDate' : IDL.Int,
  'resignOldPharmacist' : IDL.Bool,
  'proprietorName' : IDL.Text,
  'firmAddress' : IDL.Text,
  'renewalDate' : IDL.Opt(IDL.Int),
  'alterationProposedArea' : IDL.Opt(IDL.Float64),
});
export const CreateApplicationInput = IDL.Record({
  'status' : ApplicationStatus,
  'expectedCompletionDate' : IDL.Opt(IDL.Int),
  'serviceType' : ServiceType,
  'fdaAddress' : IDL.Text,
  'businessTypeData' : IDL.Opt(BusinessTypeData),
  'amountCollected' : IDL.Nat,
  'businessName' : IDL.Text,
  'businessType' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'totalFees' : IDL.Nat,
  'selectedFeeTemplates' : IDL.Vec(IDL.Nat),
  'email' : IDL.Text,
  'firmId' : IDL.Text,
  'applicationDate' : IDL.Int,
  'proprietorName' : IDL.Text,
  'firmAddress' : IDL.Text,
  'renewalDate' : IDL.Opt(IDL.Int),
});
export const BillLineItem = IDL.Record({
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const PaymentMode = IDL.Variant({
  'UPI' : IDL.Null,
  'Card' : IDL.Null,
  'Cash' : IDL.Null,
  'BankTransfer' : IDL.Null,
  'Other' : IDL.Null,
  'Cheque' : IDL.Null,
});
export const BillStatus = IDL.Variant({
  'unpaid' : IDL.Null,
  'partiallyPaid' : IDL.Null,
  'fullyPaid' : IDL.Null,
});
export const Bill = IDL.Record({
  'id' : IDL.Nat,
  'status' : BillStatus,
  'lineItems' : IDL.Vec(BillLineItem),
  'applicationId' : IDL.Nat,
  'balancePending' : IDL.Float64,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'billNumber' : IDL.Text,
  'paymentDate' : IDL.Int,
  'paymentMode' : PaymentMode,
  'paymentReceived' : IDL.Float64,
  'paidAmount' : IDL.Float64,
  'pendingAmount' : IDL.Float64,
});
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'expenseDate' : IDL.Int,
  'applicationId' : IDL.Text,
  'createdAt' : IDL.Int,
  'referenceNo' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'paymentMode' : PaymentMode,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const FeeItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'defaultAmount' : IDL.Float64,
});
export const FeeTemplate = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : IDL.Opt(ServiceType),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Receipt = IDL.Record({
  'id' : IDL.Text,
  'receiptDate' : IDL.Int,
  'applicationId' : IDL.Text,
  'createdAt' : IDL.Int,
  'referenceNo' : IDL.Opt(IDL.Text),
  'firmName' : IDL.Text,
  'firmId' : IDL.Text,
  'paymentMode' : PaymentMode,
  'amountReceived' : IDL.Float64,
  'remarks' : IDL.Opt(IDL.Text),
  'billId' : IDL.Text,
  'receiptNumber' : IDL.Text,
});
export const ServiceCharge = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : ServiceType,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Role = IDL.Variant({
  'Staff' : IDL.Null,
  'Admin' : IDL.Null,
  'Manager' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'role' : Role,
  'isActive' : IDL.Bool,
});
export const LedgerEntry = IDL.Record({
  'transactionType' : IDL.Text,
  'applicationId' : IDL.Text,
  'date' : IDL.Int,
  'reference' : IDL.Text,
  'description' : IDL.Text,
  'credit' : IDL.Float64,
  'debit' : IDL.Float64,
});
export const ReportFilter = IDL.Record({
  'status' : IDL.Opt(ApplicationStatus),
  'serviceType' : IDL.Opt(ServiceType),
  'dateTo' : IDL.Opt(IDL.Int),
  'renewalDaysAhead' : IDL.Opt(IDL.Nat),
  'dateFrom' : IDL.Opt(IDL.Int),
});
export const AppSummary = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'expectedCompletionDate' : IDL.Opt(IDL.Int),
  'serviceType' : ServiceType,
  'applicationId' : IDL.Text,
  'businessName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'firmId' : IDL.Text,
  'amountPending' : IDL.Nat,
  'proprietorName' : IDL.Text,
  'renewalDate' : IDL.Opt(IDL.Int),
});
export const CompanyInfo = IDL.Record({
  'fdaAddress' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ServiceTypeCount = IDL.Record({
  'serviceType' : ServiceType,
  'count' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'feesPendingCount' : IDL.Nat,
  'submitted' : IDL.Nat,
  'pending' : IDL.Nat,
  'upcomingDeadlines' : IDL.Vec(AppSummary),
  'completed' : IDL.Nat,
  'recentActivity' : IDL.Vec(ActivityEntry),
  'serviceTypeStats' : IDL.Vec(ServiceTypeCount),
  'pendingFeesTotal' : IDL.Nat,
  'documentsPendingCount' : IDL.Nat,
  'inProgress' : IDL.Nat,
  'onHold' : IDL.Nat,
  'totalApplications' : IDL.Nat,
});
export const FdaOfficeDetails = IDL.Record({
  'contact' : IDL.Text,
  'officeName' : IDL.Text,
  'officerName' : IDL.Text,
  'address' : IDL.Text,
});
export const FeesReport = IDL.Record({
  'totalCollected' : IDL.Nat,
  'totalBilled' : IDL.Nat,
  'applications' : IDL.Vec(AppSummary),
  'totalPending' : IDL.Nat,
});
export const PharmacistDetails = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'registrationNumber' : IDL.Text,
  'address' : IDL.Text,
  'qualification' : IDL.Text,
});
export const RenewalReport = IDL.Record({
  'applications' : IDL.Vec(AppSummary),
});
export const ApplicationFilters = IDL.Record({
  'status' : IDL.Opt(ApplicationStatus),
  'serviceType' : IDL.Opt(ServiceType),
  'dateTo' : IDL.Opt(IDL.Int),
  'dateFrom' : IDL.Opt(IDL.Int),
});
export const LoginResult = IDL.Record({
  'user' : UserPublic,
  'sessionToken' : IDL.Text,
});
export const SearchFilter = IDL.Record({
  'status' : IDL.Opt(ApplicationStatus),
  'serviceType' : IDL.Opt(ServiceType),
  'dateTo' : IDL.Opt(IDL.Int),
  'searchText' : IDL.Text,
  'dateFrom' : IDL.Opt(IDL.Int),
});
export const UpdateApplicationInput = IDL.Record({
  'id' : IDL.Nat,
  'alterationOldArea' : IDL.Opt(IDL.Float64),
  'status' : IDL.Opt(ApplicationStatus),
  'expectedCompletionDate' : IDL.Opt(IDL.Int),
  'serviceType' : IDL.Opt(ServiceType),
  'directLink' : IDL.Opt(IDL.Text),
  'fdaAddress' : IDL.Opt(IDL.Text),
  'businessTypeData' : IDL.Opt(BusinessTypeData),
  'amountCollected' : IDL.Opt(IDL.Nat),
  'businessName' : IDL.Opt(IDL.Text),
  'businessType' : IDL.Opt(IDL.Text),
  'mobileNumber' : IDL.Opt(IDL.Text),
  'totalFees' : IDL.Opt(IDL.Nat),
  'selectedFeeTemplates' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'oldPharmacistName' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'changePremiseNewAddress' : IDL.Opt(IDL.Text),
  'firmId' : IDL.Opt(IDL.Text),
  'oldPharmacistResignationDate' : IDL.Opt(IDL.Text),
  'firmPassword' : IDL.Opt(IDL.Text),
  'oldPharmacistRegNo' : IDL.Opt(IDL.Text),
  'changePremiseOldAddress' : IDL.Opt(IDL.Text),
  'applicationDate' : IDL.Opt(IDL.Int),
  'resignOldPharmacist' : IDL.Opt(IDL.Bool),
  'proprietorName' : IDL.Opt(IDL.Text),
  'firmAddress' : IDL.Opt(IDL.Text),
  'renewalDate' : IDL.Opt(IDL.Int),
  'alterationProposedArea' : IDL.Opt(IDL.Float64),
});
export const UpdateDocumentInput = IDL.Record({
  'isChecked' : IDL.Bool,
  'applicationId' : IDL.Nat,
  'documentId' : IDL.Nat,
});
export const UserUpdate = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'role' : IDL.Opt(Role),
  'isActive' : IDL.Opt(IDL.Bool),
});
export const SessionData = IDL.Record({
  'expiresAt' : IDL.Int,
  'userId' : IDL.Nat,
  'role' : Role,
});

export const idlService = IDL.Service({
  'addApplicationPharmacist' : IDL.Func(
      [IDL.Nat, ApplicationPharmacist],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'addCustomDocumentItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'addNote' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'addPortalCredential' : IDL.Func(
      [IDL.Nat, PortalCredential],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'changePassword' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createApplication' : IDL.Func(
      [CreateApplicationInput],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'createBill' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Vec(BillLineItem),
        IDL.Float64,
        PaymentMode,
        IDL.Int,
      ],
      [IDL.Variant({ 'ok' : Bill, 'err' : IDL.Text })],
      [],
    ),
  'createExpense' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        PaymentMode,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : Expense, 'err' : IDL.Text })],
      [],
    ),
  'createFeeItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Float64, IDL.Text],
      [IDL.Variant({ 'ok' : FeeItem, 'err' : IDL.Text })],
      [],
    ),
  'createFeeTemplate' : IDL.Func(
      [IDL.Text, IDL.Opt(ServiceType), IDL.Nat, IDL.Text],
      [FeeTemplate],
      [],
    ),
  'createReceipt' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Float64,
        PaymentMode,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : Receipt, 'err' : IDL.Text })],
      [],
    ),
  'createServiceCharge' : IDL.Func(
      [IDL.Text, ServiceType, IDL.Text, IDL.Float64],
      [IDL.Variant({ 'ok' : ServiceCharge, 'err' : IDL.Text })],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Text],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'deleteApplication' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteFeeItem' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteFeeTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteServiceCharge' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteUser' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getApplication' : IDL.Func([IDL.Nat], [IDL.Opt(Application)], ['query']),
  'getApplicationLedger' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(LedgerEntry)],
      ['query'],
    ),
  'getApplicationPharmacists' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Vec(ApplicationPharmacist),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getApplicationPlanLayout' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Opt(PlanLayoutDetails), 'err' : IDL.Text })],
      ['query'],
    ),
  'getApplicationStatusReport' : IDL.Func(
      [ReportFilter],
      [IDL.Vec(AppSummary)],
      ['query'],
    ),
  'getApplicationsForReport' : IDL.Func(
      [ReportFilter],
      [IDL.Vec(AppSummary)],
      ['query'],
    ),
  'getBill' : IDL.Func([IDL.Nat], [IDL.Opt(Bill)], ['query']),
  'getBillsByApplication' : IDL.Func([IDL.Nat], [IDL.Vec(Bill)], ['query']),
  'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getExpensesByApplication' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getFdaOfficeDetails' : IDL.Func([], [IDL.Opt(FdaOfficeDetails)], ['query']),
  'getFeesCollectionReport' : IDL.Func([ReportFilter], [FeesReport], ['query']),
  'getFeesReport' : IDL.Func([ReportFilter], [FeesReport], ['query']),
  'getMonthlyCollection' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Receipt)],
      ['query'],
    ),
  'getPharmacistDetails' : IDL.Func(
      [],
      [IDL.Opt(PharmacistDetails)],
      ['query'],
    ),
  'getPortalCredentials' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(PortalCredential), 'err' : IDL.Text })],
      ['query'],
    ),
  'getReceiptsByApplication' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Receipt)],
      ['query'],
    ),
  'getReceiptsByBill' : IDL.Func([IDL.Text], [IDL.Vec(Receipt)], ['query']),
  'getRenewalReminders' : IDL.Func([IDL.Nat], [IDL.Vec(AppSummary)], ['query']),
  'getRenewalRemindersReport' : IDL.Func([IDL.Nat], [RenewalReport], ['query']),
  'getServiceChargesByServiceType' : IDL.Func(
      [ServiceType],
      [IDL.Vec(ServiceCharge)],
      ['query'],
    ),
  'isFirstRun' : IDL.Func([], [IDL.Bool], ['query']),
  'listApplications' : IDL.Func(
      [ApplicationFilters],
      [IDL.Vec(AppSummary)],
      ['query'],
    ),
  'listFeeItems' : IDL.Func([], [IDL.Vec(FeeItem)], ['query']),
  'listFeeTemplates' : IDL.Func([], [IDL.Vec(FeeTemplate)], ['query']),
  'listServiceCharges' : IDL.Func([], [IDL.Vec(ServiceCharge)], ['query']),
  'listUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(UserPublic), 'err' : IDL.Text })],
      [],
    ),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : LoginResult, 'err' : IDL.Text })],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [], []),
  'removeApplicationPharmacist' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'removeCustomDocumentItem' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'removePortalCredential' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'resetAdminCredentials' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'searchApplications' : IDL.Func(
      [SearchFilter],
      [IDL.Vec(AppSummary)],
      ['query'],
    ),
  'setApplicationPlanLayout' : IDL.Func(
      [IDL.Nat, PlanLayoutDetails],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'setCompanyInfo' : IDL.Func([CompanyInfo], [], []),
  'setFdaOfficeDetails' : IDL.Func([IDL.Text, FdaOfficeDetails], [], []),
  'setPharmacistDetails' : IDL.Func([IDL.Text, PharmacistDetails], [], []),
  'setupAdmin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'updateApplication' : IDL.Func(
      [UpdateApplicationInput],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'updateApplicationPharmacist' : IDL.Func(
      [IDL.Nat, IDL.Text, ApplicationPharmacist],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'updateBillFromReceipt' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : Bill, 'err' : IDL.Text })],
      [],
    ),
  'updateDocumentItem' : IDL.Func(
      [UpdateDocumentInput],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'updateFeeItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Opt(IDL.Text)),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : FeeItem, 'err' : IDL.Text })],
      [],
    ),
  'updateFeeTemplate' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Opt(ServiceType)),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Opt(FeeTemplate)],
      [],
    ),
  'updatePortalCredential' : IDL.Func(
      [IDL.Nat, IDL.Text, PortalCredential],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'updatePortalCredentials' : IDL.Func(
      [IDL.Text, IDL.Vec(PortalCredential)],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'updateServiceCharge' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Opt(ServiceType),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Float64),
      ],
      [IDL.Variant({ 'ok' : ServiceCharge, 'err' : IDL.Text })],
      [],
    ),
  'updateUser' : IDL.Func(
      [IDL.Text, IDL.Nat, UserUpdate],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(SessionData)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationPharmacist = IDL.Record({
    'id' : IDL.Text,
    'dateOfLeaving' : IDL.Text,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'dateOfJoining' : IDL.Text,
    'address' : IDL.Text,
    'resignationDate' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'New' : IDL.Null,
    'OnHold' : IDL.Null,
    'UnderReview' : IDL.Null,
    'FeesReceived' : IDL.Null,
    'DocumentsCollected' : IDL.Null,
    'DocumentsPending' : IDL.Null,
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'ApplicationFiled' : IDL.Null,
    'Completed' : IDL.Null,
    'FeesPending' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'FoodLicenceRenewal' : IDL.Null,
    'DrugLicenceChangePremise' : IDL.Null,
    'MSMEUdyam' : IDL.Null,
    'DrugLicenceNewFirm' : IDL.Null,
    'GSTRegistration' : IDL.Null,
    'DrugLicenceAlterationOfPremise' : IDL.Null,
    'DrugLicenceRemovePharmacist' : IDL.Null,
    'DrugLicenceAddPharmacist' : IDL.Null,
    'FoodLicenceNew' : IDL.Null,
    'Other' : IDL.Null,
    'DrugLicenceChangeConstitution' : IDL.Null,
    'DrugLicenceRenewal' : IDL.Null,
  });
  const DocumentItem = IDL.Record({
    'id' : IDL.Nat,
    'isChecked' : IDL.Bool,
    'name' : IDL.Text,
    'checkedAt' : IDL.Opt(IDL.Int),
    'category' : IDL.Text,
  });
  const RoomDetail = IDL.Record({
    'whichSide' : IDL.Opt(IDL.Text),
    'length' : IDL.Float64,
    'width' : IDL.Float64,
    'roomName' : IDL.Opt(IDL.Text),
    'entranceSide' : IDL.Opt(IDL.Text),
    'entranceType' : IDL.Text,
  });
  const PlanLayoutDetails = IDL.Record({
    'boundaryEast' : IDL.Text,
    'boundaryWest' : IDL.Text,
    'frontOfShop' : IDL.Text,
    'premisesWidth' : IDL.Float64,
    'premisesLength' : IDL.Float64,
    'boundarySouth' : IDL.Text,
    'boundaryNorth' : IDL.Text,
    'rooms' : IDL.Vec(RoomDetail),
  });
  const PersonEntry = IDL.Record({
    'id' : IDL.Text,
    'din' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'aadhaarNo' : IDL.Text,
    'address' : IDL.Text,
    'panNo' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const TrusteeEntry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'aadhaarNo' : IDL.Text,
    'address' : IDL.Text,
    'panNo' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const BusinessTypeData = IDL.Variant({
    'llp' : IDL.Record({ 'designatedPartners' : IDL.Vec(PersonEntry) }),
    'ltd' : IDL.Record({
      'cin' : IDL.Text,
      'directors' : IDL.Vec(PersonEntry),
      'registeredOfficeAddress' : IDL.Text,
    }),
    'pvtLtd' : IDL.Record({
      'cin' : IDL.Text,
      'directors' : IDL.Vec(PersonEntry),
      'registeredOfficeAddress' : IDL.Text,
    }),
    'trust' : IDL.Record({
      'trustName' : IDL.Text,
      'trustees' : IDL.Vec(TrusteeEntry),
      'registrationNo' : IDL.Text,
    }),
    'other' : IDL.Record({
      'otherDescription' : IDL.Text,
      'authorizedPersonName' : IDL.Text,
      'authorizedPersonMobile' : IDL.Text,
      'authorizedPersonAadhaar' : IDL.Text,
      'authorizedPersonAddress' : IDL.Text,
      'authorizedPersonPan' : IDL.Text,
    }),
    'partnership' : IDL.Record({ 'partners' : IDL.Vec(PersonEntry) }),
    'society' : IDL.Record({
      'trustees' : IDL.Vec(TrusteeEntry),
      'registrationNo' : IDL.Text,
      'societyName' : IDL.Text,
    }),
    'proprietary' : IDL.Record({
      'proprietorAddress' : IDL.Text,
      'dateOfBirth' : IDL.Text,
      'proprietorMobile' : IDL.Text,
      'aadhaarNo' : IDL.Text,
      'panNo' : IDL.Text,
      'proprietorEmail' : IDL.Text,
      'proprietorName' : IDL.Text,
    }),
  });
  const ActivityEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const NoteEntry = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
  });
  const PortalCredential = IDL.Record({
    'id' : IDL.Text,
    'portalName' : IDL.Text,
    'directLink' : IDL.Text,
    'userId' : IDL.Text,
    'password' : IDL.Text,
  });
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'alterationOldArea' : IDL.Opt(IDL.Float64),
    'status' : ApplicationStatus,
    'expectedCompletionDate' : IDL.Opt(IDL.Int),
    'serviceType' : ServiceType,
    'directLink' : IDL.Opt(IDL.Text),
    'documents' : IDL.Vec(DocumentItem),
    'fdaAddress' : IDL.Text,
    'planLayoutDetails' : IDL.Opt(PlanLayoutDetails),
    'businessTypeData' : IDL.Opt(BusinessTypeData),
    'applicationId' : IDL.Text,
    'amountCollected' : IDL.Nat,
    'createdAt' : IDL.Int,
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'totalFees' : IDL.Nat,
    'selectedFeeTemplates' : IDL.Vec(IDL.Nat),
    'oldPharmacistName' : IDL.Text,
    'email' : IDL.Text,
    'activityLog' : IDL.Vec(ActivityEntry),
    'updatedAt' : IDL.Int,
    'changePremiseNewAddress' : IDL.Opt(IDL.Text),
    'firmId' : IDL.Text,
    'oldPharmacistResignationDate' : IDL.Text,
    'notes' : IDL.Vec(NoteEntry),
    'firmPassword' : IDL.Opt(IDL.Text),
    'pharmacists' : IDL.Vec(ApplicationPharmacist),
    'oldPharmacistRegNo' : IDL.Text,
    'amountPending' : IDL.Nat,
    'portalCredentials' : IDL.Vec(PortalCredential),
    'changePremiseOldAddress' : IDL.Opt(IDL.Text),
    'applicationDate' : IDL.Int,
    'resignOldPharmacist' : IDL.Bool,
    'proprietorName' : IDL.Text,
    'firmAddress' : IDL.Text,
    'renewalDate' : IDL.Opt(IDL.Int),
    'alterationProposedArea' : IDL.Opt(IDL.Float64),
  });
  const CreateApplicationInput = IDL.Record({
    'status' : ApplicationStatus,
    'expectedCompletionDate' : IDL.Opt(IDL.Int),
    'serviceType' : ServiceType,
    'fdaAddress' : IDL.Text,
    'businessTypeData' : IDL.Opt(BusinessTypeData),
    'amountCollected' : IDL.Nat,
    'businessName' : IDL.Text,
    'businessType' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'totalFees' : IDL.Nat,
    'selectedFeeTemplates' : IDL.Vec(IDL.Nat),
    'email' : IDL.Text,
    'firmId' : IDL.Text,
    'applicationDate' : IDL.Int,
    'proprietorName' : IDL.Text,
    'firmAddress' : IDL.Text,
    'renewalDate' : IDL.Opt(IDL.Int),
  });
  const BillLineItem = IDL.Record({
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const PaymentMode = IDL.Variant({
    'UPI' : IDL.Null,
    'Card' : IDL.Null,
    'Cash' : IDL.Null,
    'BankTransfer' : IDL.Null,
    'Other' : IDL.Null,
    'Cheque' : IDL.Null,
  });
  const BillStatus = IDL.Variant({
    'unpaid' : IDL.Null,
    'partiallyPaid' : IDL.Null,
    'fullyPaid' : IDL.Null,
  });
  const Bill = IDL.Record({
    'id' : IDL.Nat,
    'status' : BillStatus,
    'lineItems' : IDL.Vec(BillLineItem),
    'applicationId' : IDL.Nat,
    'balancePending' : IDL.Float64,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'billNumber' : IDL.Text,
    'paymentDate' : IDL.Int,
    'paymentMode' : PaymentMode,
    'paymentReceived' : IDL.Float64,
    'paidAmount' : IDL.Float64,
    'pendingAmount' : IDL.Float64,
  });
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'expenseDate' : IDL.Int,
    'applicationId' : IDL.Text,
    'createdAt' : IDL.Int,
    'referenceNo' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'paymentMode' : PaymentMode,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const FeeItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'defaultAmount' : IDL.Float64,
  });
  const FeeTemplate = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : IDL.Opt(ServiceType),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Receipt = IDL.Record({
    'id' : IDL.Text,
    'receiptDate' : IDL.Int,
    'applicationId' : IDL.Text,
    'createdAt' : IDL.Int,
    'referenceNo' : IDL.Opt(IDL.Text),
    'firmName' : IDL.Text,
    'firmId' : IDL.Text,
    'paymentMode' : PaymentMode,
    'amountReceived' : IDL.Float64,
    'remarks' : IDL.Opt(IDL.Text),
    'billId' : IDL.Text,
    'receiptNumber' : IDL.Text,
  });
  const ServiceCharge = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : ServiceType,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Role = IDL.Variant({
    'Staff' : IDL.Null,
    'Admin' : IDL.Null,
    'Manager' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'role' : Role,
    'isActive' : IDL.Bool,
  });
  const LedgerEntry = IDL.Record({
    'transactionType' : IDL.Text,
    'applicationId' : IDL.Text,
    'date' : IDL.Int,
    'reference' : IDL.Text,
    'description' : IDL.Text,
    'credit' : IDL.Float64,
    'debit' : IDL.Float64,
  });
  const ReportFilter = IDL.Record({
    'status' : IDL.Opt(ApplicationStatus),
    'serviceType' : IDL.Opt(ServiceType),
    'dateTo' : IDL.Opt(IDL.Int),
    'renewalDaysAhead' : IDL.Opt(IDL.Nat),
    'dateFrom' : IDL.Opt(IDL.Int),
  });
  const AppSummary = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'expectedCompletionDate' : IDL.Opt(IDL.Int),
    'serviceType' : ServiceType,
    'applicationId' : IDL.Text,
    'businessName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'firmId' : IDL.Text,
    'amountPending' : IDL.Nat,
    'proprietorName' : IDL.Text,
    'renewalDate' : IDL.Opt(IDL.Int),
  });
  const CompanyInfo = IDL.Record({
    'fdaAddress' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ServiceTypeCount = IDL.Record({
    'serviceType' : ServiceType,
    'count' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'feesPendingCount' : IDL.Nat,
    'submitted' : IDL.Nat,
    'pending' : IDL.Nat,
    'upcomingDeadlines' : IDL.Vec(AppSummary),
    'completed' : IDL.Nat,
    'recentActivity' : IDL.Vec(ActivityEntry),
    'serviceTypeStats' : IDL.Vec(ServiceTypeCount),
    'pendingFeesTotal' : IDL.Nat,
    'documentsPendingCount' : IDL.Nat,
    'inProgress' : IDL.Nat,
    'onHold' : IDL.Nat,
    'totalApplications' : IDL.Nat,
  });
  const FdaOfficeDetails = IDL.Record({
    'contact' : IDL.Text,
    'officeName' : IDL.Text,
    'officerName' : IDL.Text,
    'address' : IDL.Text,
  });
  const FeesReport = IDL.Record({
    'totalCollected' : IDL.Nat,
    'totalBilled' : IDL.Nat,
    'applications' : IDL.Vec(AppSummary),
    'totalPending' : IDL.Nat,
  });
  const PharmacistDetails = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'registrationNumber' : IDL.Text,
    'address' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const RenewalReport = IDL.Record({ 'applications' : IDL.Vec(AppSummary) });
  const ApplicationFilters = IDL.Record({
    'status' : IDL.Opt(ApplicationStatus),
    'serviceType' : IDL.Opt(ServiceType),
    'dateTo' : IDL.Opt(IDL.Int),
    'dateFrom' : IDL.Opt(IDL.Int),
  });
  const LoginResult = IDL.Record({
    'user' : UserPublic,
    'sessionToken' : IDL.Text,
  });
  const SearchFilter = IDL.Record({
    'status' : IDL.Opt(ApplicationStatus),
    'serviceType' : IDL.Opt(ServiceType),
    'dateTo' : IDL.Opt(IDL.Int),
    'searchText' : IDL.Text,
    'dateFrom' : IDL.Opt(IDL.Int),
  });
  const UpdateApplicationInput = IDL.Record({
    'id' : IDL.Nat,
    'alterationOldArea' : IDL.Opt(IDL.Float64),
    'status' : IDL.Opt(ApplicationStatus),
    'expectedCompletionDate' : IDL.Opt(IDL.Int),
    'serviceType' : IDL.Opt(ServiceType),
    'directLink' : IDL.Opt(IDL.Text),
    'fdaAddress' : IDL.Opt(IDL.Text),
    'businessTypeData' : IDL.Opt(BusinessTypeData),
    'amountCollected' : IDL.Opt(IDL.Nat),
    'businessName' : IDL.Opt(IDL.Text),
    'businessType' : IDL.Opt(IDL.Text),
    'mobileNumber' : IDL.Opt(IDL.Text),
    'totalFees' : IDL.Opt(IDL.Nat),
    'selectedFeeTemplates' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'oldPharmacistName' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'changePremiseNewAddress' : IDL.Opt(IDL.Text),
    'firmId' : IDL.Opt(IDL.Text),
    'oldPharmacistResignationDate' : IDL.Opt(IDL.Text),
    'firmPassword' : IDL.Opt(IDL.Text),
    'oldPharmacistRegNo' : IDL.Opt(IDL.Text),
    'changePremiseOldAddress' : IDL.Opt(IDL.Text),
    'applicationDate' : IDL.Opt(IDL.Int),
    'resignOldPharmacist' : IDL.Opt(IDL.Bool),
    'proprietorName' : IDL.Opt(IDL.Text),
    'firmAddress' : IDL.Opt(IDL.Text),
    'renewalDate' : IDL.Opt(IDL.Int),
    'alterationProposedArea' : IDL.Opt(IDL.Float64),
  });
  const UpdateDocumentInput = IDL.Record({
    'isChecked' : IDL.Bool,
    'applicationId' : IDL.Nat,
    'documentId' : IDL.Nat,
  });
  const UserUpdate = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'role' : IDL.Opt(Role),
    'isActive' : IDL.Opt(IDL.Bool),
  });
  const SessionData = IDL.Record({
    'expiresAt' : IDL.Int,
    'userId' : IDL.Nat,
    'role' : Role,
  });
  
  return IDL.Service({
    'addApplicationPharmacist' : IDL.Func(
        [IDL.Nat, ApplicationPharmacist],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'addCustomDocumentItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'addNote' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'addPortalCredential' : IDL.Func(
        [IDL.Nat, PortalCredential],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'changePassword' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createApplication' : IDL.Func(
        [CreateApplicationInput],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'createBill' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Vec(BillLineItem),
          IDL.Float64,
          PaymentMode,
          IDL.Int,
        ],
        [IDL.Variant({ 'ok' : Bill, 'err' : IDL.Text })],
        [],
      ),
    'createExpense' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          PaymentMode,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : Expense, 'err' : IDL.Text })],
        [],
      ),
    'createFeeItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Float64, IDL.Text],
        [IDL.Variant({ 'ok' : FeeItem, 'err' : IDL.Text })],
        [],
      ),
    'createFeeTemplate' : IDL.Func(
        [IDL.Text, IDL.Opt(ServiceType), IDL.Nat, IDL.Text],
        [FeeTemplate],
        [],
      ),
    'createReceipt' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Float64,
          PaymentMode,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : Receipt, 'err' : IDL.Text })],
        [],
      ),
    'createServiceCharge' : IDL.Func(
        [IDL.Text, ServiceType, IDL.Text, IDL.Float64],
        [IDL.Variant({ 'ok' : ServiceCharge, 'err' : IDL.Text })],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Text],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'deleteApplication' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteFeeItem' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteFeeTemplate' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteServiceCharge' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteUser' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getApplication' : IDL.Func([IDL.Nat], [IDL.Opt(Application)], ['query']),
    'getApplicationLedger' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(LedgerEntry)],
        ['query'],
      ),
    'getApplicationPharmacists' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Vec(ApplicationPharmacist),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getApplicationPlanLayout' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Opt(PlanLayoutDetails), 'err' : IDL.Text })],
        ['query'],
      ),
    'getApplicationStatusReport' : IDL.Func(
        [ReportFilter],
        [IDL.Vec(AppSummary)],
        ['query'],
      ),
    'getApplicationsForReport' : IDL.Func(
        [ReportFilter],
        [IDL.Vec(AppSummary)],
        ['query'],
      ),
    'getBill' : IDL.Func([IDL.Nat], [IDL.Opt(Bill)], ['query']),
    'getBillsByApplication' : IDL.Func([IDL.Nat], [IDL.Vec(Bill)], ['query']),
    'getCompanyInfo' : IDL.Func([], [CompanyInfo], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getExpensesByApplication' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getFdaOfficeDetails' : IDL.Func(
        [],
        [IDL.Opt(FdaOfficeDetails)],
        ['query'],
      ),
    'getFeesCollectionReport' : IDL.Func(
        [ReportFilter],
        [FeesReport],
        ['query'],
      ),
    'getFeesReport' : IDL.Func([ReportFilter], [FeesReport], ['query']),
    'getMonthlyCollection' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Receipt)],
        ['query'],
      ),
    'getPharmacistDetails' : IDL.Func(
        [],
        [IDL.Opt(PharmacistDetails)],
        ['query'],
      ),
    'getPortalCredentials' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(PortalCredential), 'err' : IDL.Text })],
        ['query'],
      ),
    'getReceiptsByApplication' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Receipt)],
        ['query'],
      ),
    'getReceiptsByBill' : IDL.Func([IDL.Text], [IDL.Vec(Receipt)], ['query']),
    'getRenewalReminders' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AppSummary)],
        ['query'],
      ),
    'getRenewalRemindersReport' : IDL.Func(
        [IDL.Nat],
        [RenewalReport],
        ['query'],
      ),
    'getServiceChargesByServiceType' : IDL.Func(
        [ServiceType],
        [IDL.Vec(ServiceCharge)],
        ['query'],
      ),
    'isFirstRun' : IDL.Func([], [IDL.Bool], ['query']),
    'listApplications' : IDL.Func(
        [ApplicationFilters],
        [IDL.Vec(AppSummary)],
        ['query'],
      ),
    'listFeeItems' : IDL.Func([], [IDL.Vec(FeeItem)], ['query']),
    'listFeeTemplates' : IDL.Func([], [IDL.Vec(FeeTemplate)], ['query']),
    'listServiceCharges' : IDL.Func([], [IDL.Vec(ServiceCharge)], ['query']),
    'listUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(UserPublic), 'err' : IDL.Text })],
        [],
      ),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : LoginResult, 'err' : IDL.Text })],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [], []),
    'removeApplicationPharmacist' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'removeCustomDocumentItem' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'removePortalCredential' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'resetAdminCredentials' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'searchApplications' : IDL.Func(
        [SearchFilter],
        [IDL.Vec(AppSummary)],
        ['query'],
      ),
    'setApplicationPlanLayout' : IDL.Func(
        [IDL.Nat, PlanLayoutDetails],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'setCompanyInfo' : IDL.Func([CompanyInfo], [], []),
    'setFdaOfficeDetails' : IDL.Func([IDL.Text, FdaOfficeDetails], [], []),
    'setPharmacistDetails' : IDL.Func([IDL.Text, PharmacistDetails], [], []),
    'setupAdmin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'updateApplication' : IDL.Func(
        [UpdateApplicationInput],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'updateApplicationPharmacist' : IDL.Func(
        [IDL.Nat, IDL.Text, ApplicationPharmacist],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'updateBillFromReceipt' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : Bill, 'err' : IDL.Text })],
        [],
      ),
    'updateDocumentItem' : IDL.Func(
        [UpdateDocumentInput],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'updateFeeItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Opt(IDL.Text)),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : FeeItem, 'err' : IDL.Text })],
        [],
      ),
    'updateFeeTemplate' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Opt(ServiceType)),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Opt(FeeTemplate)],
        [],
      ),
    'updatePortalCredential' : IDL.Func(
        [IDL.Nat, IDL.Text, PortalCredential],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'updatePortalCredentials' : IDL.Func(
        [IDL.Text, IDL.Vec(PortalCredential)],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'updateServiceCharge' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Opt(ServiceType),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Float64),
        ],
        [IDL.Variant({ 'ok' : ServiceCharge, 'err' : IDL.Text })],
        [],
      ),
    'updateUser' : IDL.Func(
        [IDL.Text, IDL.Nat, UserUpdate],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Opt(SessionData)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };