/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry {
  'id' : bigint,
  'action' : string,
  'description' : string,
  'timestamp' : bigint,
}
export interface AppSummary {
  'id' : bigint,
  'status' : ApplicationStatus,
  'expectedCompletionDate' : [] | [bigint],
  'serviceType' : ServiceType,
  'applicationId' : string,
  'businessName' : string,
  'updatedAt' : bigint,
  'firmId' : string,
  'amountPending' : bigint,
  'proprietorName' : string,
  'renewalDate' : [] | [bigint],
}
export interface Application {
  'id' : bigint,
  'alterationOldArea' : [] | [number],
  'status' : ApplicationStatus,
  'expectedCompletionDate' : [] | [bigint],
  'serviceType' : ServiceType,
  'directLink' : [] | [string],
  'documents' : Array<DocumentItem>,
  'fdaAddress' : string,
  'planLayoutDetails' : [] | [PlanLayoutDetails],
  'businessTypeData' : [] | [BusinessTypeData],
  'applicationId' : string,
  'amountCollected' : bigint,
  'createdAt' : bigint,
  'businessName' : string,
  'businessType' : string,
  'mobileNumber' : string,
  'totalFees' : bigint,
  'selectedFeeTemplates' : Array<bigint>,
  'oldPharmacistName' : string,
  'email' : string,
  'activityLog' : Array<ActivityEntry>,
  'updatedAt' : bigint,
  'changePremiseNewAddress' : [] | [string],
  'firmId' : string,
  'oldPharmacistResignationDate' : string,
  'notes' : Array<NoteEntry>,
  'firmPassword' : [] | [string],
  'pharmacists' : Array<ApplicationPharmacist>,
  'oldPharmacistRegNo' : string,
  'amountPending' : bigint,
  'portalCredentials' : Array<PortalCredential>,
  'changePremiseOldAddress' : [] | [string],
  'applicationDate' : bigint,
  'resignOldPharmacist' : boolean,
  'proprietorName' : string,
  'firmAddress' : string,
  'renewalDate' : [] | [bigint],
  'alterationProposedArea' : [] | [number],
}
export interface ApplicationFilters {
  'status' : [] | [ApplicationStatus],
  'serviceType' : [] | [ServiceType],
  'dateTo' : [] | [bigint],
  'dateFrom' : [] | [bigint],
}
export interface ApplicationPharmacist {
  'id' : string,
  'dateOfLeaving' : string,
  'fullName' : string,
  'mobileNumber' : string,
  'registrationNumber' : string,
  'dateOfJoining' : string,
  'address' : string,
  'resignationDate' : string,
  'aadhaarNumber' : string,
  'qualification' : string,
}
export type ApplicationStatus = { 'New' : null } |
  { 'OnHold' : null } |
  { 'UnderReview' : null } |
  { 'FeesReceived' : null } |
  { 'DocumentsCollected' : null } |
  { 'DocumentsPending' : null } |
  { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'ApplicationFiled' : null } |
  { 'Completed' : null } |
  { 'FeesPending' : null };
export interface Bill {
  'id' : bigint,
  'status' : BillStatus,
  'lineItems' : Array<BillLineItem>,
  'applicationId' : bigint,
  'balancePending' : number,
  'createdAt' : bigint,
  'totalAmount' : number,
  'billNumber' : string,
  'paymentDate' : bigint,
  'paymentMode' : PaymentMode,
  'paymentReceived' : number,
  'paidAmount' : number,
  'pendingAmount' : number,
}
export interface BillLineItem {
  'description' : string,
  'quantity' : bigint,
  'amount' : number,
}
export type BillStatus = { 'unpaid' : null } |
  { 'partiallyPaid' : null } |
  { 'fullyPaid' : null };
export type BusinessTypeData = {
    'llp' : { 'designatedPartners' : Array<PersonEntry> }
  } |
  {
    'ltd' : {
      'cin' : string,
      'directors' : Array<PersonEntry>,
      'registeredOfficeAddress' : string,
    }
  } |
  {
    'pvtLtd' : {
      'cin' : string,
      'directors' : Array<PersonEntry>,
      'registeredOfficeAddress' : string,
    }
  } |
  {
    'trust' : {
      'trustName' : string,
      'trustees' : Array<TrusteeEntry>,
      'registrationNo' : string,
    }
  } |
  {
    'other' : {
      'otherDescription' : string,
      'authorizedPersonName' : string,
      'authorizedPersonMobile' : string,
      'authorizedPersonAadhaar' : string,
      'authorizedPersonAddress' : string,
      'authorizedPersonPan' : string,
    }
  } |
  { 'partnership' : { 'partners' : Array<PersonEntry> } } |
  {
    'society' : {
      'trustees' : Array<TrusteeEntry>,
      'registrationNo' : string,
      'societyName' : string,
    }
  } |
  {
    'proprietary' : {
      'proprietorAddress' : string,
      'dateOfBirth' : string,
      'proprietorMobile' : string,
      'aadhaarNo' : string,
      'panNo' : string,
      'proprietorEmail' : string,
      'proprietorName' : string,
    }
  };
export interface CompanyInfo {
  'fdaAddress' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface CreateApplicationInput {
  'status' : ApplicationStatus,
  'expectedCompletionDate' : [] | [bigint],
  'serviceType' : ServiceType,
  'fdaAddress' : string,
  'businessTypeData' : [] | [BusinessTypeData],
  'amountCollected' : bigint,
  'businessName' : string,
  'businessType' : string,
  'mobileNumber' : string,
  'totalFees' : bigint,
  'selectedFeeTemplates' : Array<bigint>,
  'email' : string,
  'firmId' : string,
  'applicationDate' : bigint,
  'proprietorName' : string,
  'firmAddress' : string,
  'renewalDate' : [] | [bigint],
}
export interface DashboardStats {
  'feesPendingCount' : bigint,
  'submitted' : bigint,
  'pending' : bigint,
  'upcomingDeadlines' : Array<AppSummary>,
  'completed' : bigint,
  'recentActivity' : Array<ActivityEntry>,
  'serviceTypeStats' : Array<ServiceTypeCount>,
  'pendingFeesTotal' : bigint,
  'documentsPendingCount' : bigint,
  'inProgress' : bigint,
  'onHold' : bigint,
  'totalApplications' : bigint,
}
export interface DocumentItem {
  'id' : bigint,
  'isChecked' : boolean,
  'name' : string,
  'checkedAt' : [] | [bigint],
  'category' : string,
}
export interface Expense {
  'id' : string,
  'expenseDate' : bigint,
  'applicationId' : string,
  'createdAt' : bigint,
  'referenceNo' : [] | [string],
  'description' : string,
  'notes' : [] | [string],
  'paymentMode' : PaymentMode,
  'category' : string,
  'amount' : number,
}
export interface FdaOfficeDetails {
  'contact' : string,
  'officeName' : string,
  'officerName' : string,
  'address' : string,
}
export interface FeeItem {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : [] | [string],
  'category' : string,
  'defaultAmount' : number,
}
export interface FeeTemplate {
  'id' : bigint,
  'serviceType' : [] | [ServiceType],
  'name' : string,
  'description' : string,
  'amount' : bigint,
}
export interface FeesReport {
  'totalCollected' : bigint,
  'totalBilled' : bigint,
  'applications' : Array<AppSummary>,
  'totalPending' : bigint,
}
export interface LedgerEntry {
  'transactionType' : string,
  'applicationId' : string,
  'date' : bigint,
  'reference' : string,
  'description' : string,
  'credit' : number,
  'debit' : number,
}
export interface LoginResult { 'user' : UserPublic, 'sessionToken' : string }
export interface NoteEntry {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
}
export type PaymentMode = { 'UPI' : null } |
  { 'Card' : null } |
  { 'Cash' : null } |
  { 'BankTransfer' : null } |
  { 'Other' : null } |
  { 'Cheque' : null };
export interface PersonEntry {
  'id' : string,
  'din' : string,
  'dateOfBirth' : string,
  'name' : string,
  'email' : string,
  'aadhaarNo' : string,
  'address' : string,
  'panNo' : string,
  'mobile' : string,
}
export interface PharmacistDetails {
  'contact' : string,
  'name' : string,
  'registrationNumber' : string,
  'address' : string,
  'qualification' : string,
}
export interface PlanLayoutDetails {
  'boundaryEast' : string,
  'boundaryWest' : string,
  'frontOfShop' : string,
  'premisesWidth' : number,
  'premisesLength' : number,
  'boundarySouth' : string,
  'boundaryNorth' : string,
  'rooms' : Array<RoomDetail>,
}
export interface PortalCredential {
  'id' : string,
  'portalName' : string,
  'directLink' : string,
  'userId' : string,
  'password' : string,
}
export interface Receipt {
  'id' : string,
  'receiptDate' : bigint,
  'applicationId' : string,
  'createdAt' : bigint,
  'referenceNo' : [] | [string],
  'firmName' : string,
  'firmId' : string,
  'paymentMode' : PaymentMode,
  'amountReceived' : number,
  'remarks' : [] | [string],
  'billId' : string,
  'receiptNumber' : string,
}
export interface RenewalReport { 'applications' : Array<AppSummary> }
export interface ReportFilter {
  'status' : [] | [ApplicationStatus],
  'serviceType' : [] | [ServiceType],
  'dateTo' : [] | [bigint],
  'renewalDaysAhead' : [] | [bigint],
  'dateFrom' : [] | [bigint],
}
export type Role = { 'Staff' : null } |
  { 'Admin' : null } |
  { 'Manager' : null };
export interface RoomDetail {
  'whichSide' : [] | [string],
  'length' : number,
  'width' : number,
  'roomName' : [] | [string],
  'entranceSide' : [] | [string],
  'entranceType' : string,
}
export interface SearchFilter {
  'status' : [] | [ApplicationStatus],
  'serviceType' : [] | [ServiceType],
  'dateTo' : [] | [bigint],
  'searchText' : string,
  'dateFrom' : [] | [bigint],
}
export interface ServiceCharge {
  'id' : bigint,
  'serviceType' : ServiceType,
  'description' : string,
  'amount' : number,
}
export type ServiceType = { 'FoodLicenceRenewal' : null } |
  { 'DrugLicenceChangePremise' : null } |
  { 'MSMEUdyam' : null } |
  { 'DrugLicenceNewFirm' : null } |
  { 'GSTRegistration' : null } |
  { 'DrugLicenceAlterationOfPremise' : null } |
  { 'DrugLicenceRemovePharmacist' : null } |
  { 'DrugLicenceAddPharmacist' : null } |
  { 'FoodLicenceNew' : null } |
  { 'Other' : null } |
  { 'DrugLicenceChangeConstitution' : null } |
  { 'DrugLicenceRenewal' : null };
export interface ServiceTypeCount {
  'serviceType' : ServiceType,
  'count' : bigint,
}
export interface SessionData {
  'expiresAt' : bigint,
  'userId' : bigint,
  'role' : Role,
}
export interface TrusteeEntry {
  'id' : string,
  'name' : string,
  'email' : string,
  'aadhaarNo' : string,
  'address' : string,
  'panNo' : string,
  'mobile' : string,
}
export interface UpdateApplicationInput {
  'id' : bigint,
  'alterationOldArea' : [] | [number],
  'status' : [] | [ApplicationStatus],
  'expectedCompletionDate' : [] | [bigint],
  'serviceType' : [] | [ServiceType],
  'directLink' : [] | [string],
  'fdaAddress' : [] | [string],
  'businessTypeData' : [] | [BusinessTypeData],
  'amountCollected' : [] | [bigint],
  'businessName' : [] | [string],
  'businessType' : [] | [string],
  'mobileNumber' : [] | [string],
  'totalFees' : [] | [bigint],
  'selectedFeeTemplates' : [] | [Array<bigint>],
  'oldPharmacistName' : [] | [string],
  'email' : [] | [string],
  'changePremiseNewAddress' : [] | [string],
  'firmId' : [] | [string],
  'oldPharmacistResignationDate' : [] | [string],
  'firmPassword' : [] | [string],
  'oldPharmacistRegNo' : [] | [string],
  'changePremiseOldAddress' : [] | [string],
  'applicationDate' : [] | [bigint],
  'resignOldPharmacist' : [] | [boolean],
  'proprietorName' : [] | [string],
  'firmAddress' : [] | [string],
  'renewalDate' : [] | [bigint],
  'alterationProposedArea' : [] | [number],
}
export interface UpdateDocumentInput {
  'isChecked' : boolean,
  'applicationId' : bigint,
  'documentId' : bigint,
}
export interface UserPublic {
  'id' : bigint,
  'username' : string,
  'displayName' : string,
  'role' : Role,
  'isActive' : boolean,
}
export interface UserUpdate {
  'displayName' : [] | [string],
  'role' : [] | [Role],
  'isActive' : [] | [boolean],
}
export interface _SERVICE {
  'addApplicationPharmacist' : ActorMethod<
    [bigint, ApplicationPharmacist],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'addCustomDocumentItem' : ActorMethod<
    [bigint, string, string],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'addNote' : ActorMethod<
    [bigint, string],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'addPortalCredential' : ActorMethod<
    [bigint, PortalCredential],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  /**
   * / Change a user's password. Admin can change any; future: self-change support.
   */
  'changePassword' : ActorMethod<
    [string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createApplication' : ActorMethod<
    [CreateApplicationInput],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'createBill' : ActorMethod<
    [string, bigint, Array<BillLineItem>, number, PaymentMode, bigint],
    { 'ok' : Bill } |
      { 'err' : string }
  >,
  'createExpense' : ActorMethod<
    [
      string,
      string,
      bigint,
      string,
      string,
      number,
      PaymentMode,
      [] | [string],
      [] | [string],
    ],
    { 'ok' : Expense } |
      { 'err' : string }
  >,
  'createFeeItem' : ActorMethod<
    [string, string, [] | [string], number, string],
    { 'ok' : FeeItem } |
      { 'err' : string }
  >,
  'createFeeTemplate' : ActorMethod<
    [string, [] | [ServiceType], bigint, string],
    FeeTemplate
  >,
  'createReceipt' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      number,
      PaymentMode,
      [] | [string],
      [] | [string],
    ],
    { 'ok' : Receipt } |
      { 'err' : string }
  >,
  'createServiceCharge' : ActorMethod<
    [string, ServiceType, string, number],
    { 'ok' : ServiceCharge } |
      { 'err' : string }
  >,
  /**
   * / Create a new user. Requires Admin session.
   */
  'createUser' : ActorMethod<
    [string, string, string, Role, string],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'deleteApplication' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteFeeItem' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteFeeTemplate' : ActorMethod<[bigint], boolean>,
  'deleteServiceCharge' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  /**
   * / Delete a user. Requires Admin session. Cannot delete yourself.
   */
  'deleteUser' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getApplication' : ActorMethod<[bigint], [] | [Application]>,
  'getApplicationLedger' : ActorMethod<[string, bigint], Array<LedgerEntry>>,
  'getApplicationPharmacists' : ActorMethod<
    [bigint],
    { 'ok' : Array<ApplicationPharmacist> } |
      { 'err' : string }
  >,
  'getApplicationPlanLayout' : ActorMethod<
    [bigint],
    { 'ok' : [] | [PlanLayoutDetails] } |
      { 'err' : string }
  >,
  'getApplicationStatusReport' : ActorMethod<[ReportFilter], Array<AppSummary>>,
  'getApplicationsForReport' : ActorMethod<[ReportFilter], Array<AppSummary>>,
  'getBill' : ActorMethod<[bigint], [] | [Bill]>,
  'getBillsByApplication' : ActorMethod<[bigint], Array<Bill>>,
  'getCompanyInfo' : ActorMethod<[], CompanyInfo>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getExpensesByApplication' : ActorMethod<[string], Array<Expense>>,
  'getFdaOfficeDetails' : ActorMethod<[], [] | [FdaOfficeDetails]>,
  'getFeesCollectionReport' : ActorMethod<[ReportFilter], FeesReport>,
  'getFeesReport' : ActorMethod<[ReportFilter], FeesReport>,
  'getMonthlyCollection' : ActorMethod<[bigint, bigint], Array<Receipt>>,
  'getPharmacistDetails' : ActorMethod<[], [] | [PharmacistDetails]>,
  'getPortalCredentials' : ActorMethod<
    [bigint],
    { 'ok' : Array<PortalCredential> } |
      { 'err' : string }
  >,
  'getReceiptsByApplication' : ActorMethod<[string], Array<Receipt>>,
  'getReceiptsByBill' : ActorMethod<[string], Array<Receipt>>,
  'getRenewalReminders' : ActorMethod<[bigint], Array<AppSummary>>,
  'getRenewalRemindersReport' : ActorMethod<[bigint], RenewalReport>,
  'getServiceChargesByServiceType' : ActorMethod<
    [ServiceType],
    Array<ServiceCharge>
  >,
  /**
   * / Returns true when no users have been created yet (first-run setup).
   */
  'isFirstRun' : ActorMethod<[], boolean>,
  'listApplications' : ActorMethod<[ApplicationFilters], Array<AppSummary>>,
  'listFeeItems' : ActorMethod<[], Array<FeeItem>>,
  'listFeeTemplates' : ActorMethod<[], Array<FeeTemplate>>,
  'listServiceCharges' : ActorMethod<[], Array<ServiceCharge>>,
  /**
   * / List all users. Requires Admin session.
   */
  'listUsers' : ActorMethod<
    [string],
    { 'ok' : Array<UserPublic> } |
      { 'err' : string }
  >,
  /**
   * / Authenticate with username + passwordHash. Returns a session token valid for 24h.
   */
  'login' : ActorMethod<
    [string, string],
    { 'ok' : LoginResult } |
      { 'err' : string }
  >,
  /**
   * / Invalidate a session.
   */
  'logout' : ActorMethod<[string], undefined>,
  'removeApplicationPharmacist' : ActorMethod<
    [bigint, string],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'removeCustomDocumentItem' : ActorMethod<
    [bigint, bigint],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'removePortalCredential' : ActorMethod<
    [bigint, string],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  /**
   * / Recovery endpoint — resets credentials to username='admin' / password='12345' (SHA-256).
   * / No token required: intended for admins who have lost access.
   * / Also clears all active sessions.
   */
  'resetAdminCredentials' : ActorMethod<
    [],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'searchApplications' : ActorMethod<[SearchFilter], Array<AppSummary>>,
  'setApplicationPlanLayout' : ActorMethod<
    [bigint, PlanLayoutDetails],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'setCompanyInfo' : ActorMethod<[CompanyInfo], undefined>,
  'setFdaOfficeDetails' : ActorMethod<[string, FdaOfficeDetails], undefined>,
  'setPharmacistDetails' : ActorMethod<[string, PharmacistDetails], undefined>,
  /**
   * / Create the first Admin account. Fails if any user already exists.
   */
  'setupAdmin' : ActorMethod<
    [string, string, string],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'updateApplication' : ActorMethod<
    [UpdateApplicationInput],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'updateApplicationPharmacist' : ActorMethod<
    [bigint, string, ApplicationPharmacist],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'updateBillFromReceipt' : ActorMethod<
    [string, bigint],
    { 'ok' : Bill } |
      { 'err' : string }
  >,
  'updateDocumentItem' : ActorMethod<
    [UpdateDocumentInput],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'updateFeeItem' : ActorMethod<
    [
      string,
      string,
      [] | [string],
      [] | [[] | [string]],
      [] | [number],
      [] | [string],
    ],
    { 'ok' : FeeItem } |
      { 'err' : string }
  >,
  'updateFeeTemplate' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [[] | [ServiceType]],
      [] | [bigint],
      [] | [string],
    ],
    [] | [FeeTemplate]
  >,
  'updatePortalCredential' : ActorMethod<
    [bigint, string, PortalCredential],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'updatePortalCredentials' : ActorMethod<
    [string, Array<PortalCredential>],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'updateServiceCharge' : ActorMethod<
    [string, bigint, [] | [ServiceType], [] | [string], [] | [number]],
    { 'ok' : ServiceCharge } |
      { 'err' : string }
  >,
  /**
   * / Update a user's display name, role, or active status. Requires Admin session.
   */
  'updateUser' : ActorMethod<
    [string, bigint, UserUpdate],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  /**
   * / Validate an existing session token. Returns null if expired/not found.
   */
  'validateSession' : ActorMethod<[string], [] | [SessionData]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];